#!/usr/bin/env python3
"""
Read the pickle files generated by run.py and create some plots
"""

# pylint: disable=invalid-name

import pickle

from matplotlib import pyplot as plt

plt.rcParams.update(
    {
        "font.family": "Times New Roman",
        "font.size": 16,
    }
)


def plot_iter(itr):
    with open(f"iter{itr:03d}.pkl", "rb") as fobj:
        F1 = pickle.load(fobj)
        F2 = pickle.load(fobj)

    plt.plot(F1[:, 0], F1[:, 1], "b.")
    plt.plot(F2[:, 0], F2[:, 1], "c.")
    plt.grid()
    plt.gca().set_aspect("equal")
    left, right = plt.gca().get_xlim()
    bottom, top = plt.gca().get_ylim()
    horiz = right - left
    vert = top - bottom

    # Make the aspect ratio 1:1
    if horiz > vert:
        offset = (horiz - vert) / 2
        plt.ylim(bottom - offset, top + offset)
    elif vert > horiz:
        offset = (vert - horiz) / 2
        plt.xlim(left - offset, right + offset)

    plt.title(f"Iteration {itr}")
    plt.gca().title.set_size(16)


plt.figure(figsize=(7, 7))

plt.subplot(2, 2, 1)
plot_iter(0)

plt.subplot(2, 2, 2)
plot_iter(3)

plt.subplot(2, 2, 3)
plot_iter(10)

plt.subplot(2, 2, 4)
plot_iter(30)

plt.savefig("simulation.eps", bbox_inches="tight", pad_inches=0)
