#!/usr/bin/env python3

import json

import numpy as np
from matplotlib import pyplot as plt

# Read the pickle file generated by get_pronlen_dist.py
with open("pronlendist.json", "r", encoding="utf8") as fobj:
    pronlen_to_score = {int(key): float(val) for key, val in json.load(fobj).items()}

lengths = np.arange(1, 31)
scores = np.array([pronlen_to_score[length] for length in lengths])
scores = scores / np.sum(scores)

plt.rcParams.update({"text.usetex": True, "font.family": "Helvetica"})

plt.rcParams.update(
    {
        "font.family": "Times New Roman",
        "font.size": 16,
    }
)

plt.plot(lengths, scores, ".-")
plt.grid()
plt.xlabel("Number of phones $h$")
plt.ylabel("$P(h)$")
plt.gcf().set_figheight(4)
plt.gcf().tight_layout()  # otherwise the right y-label is slightly clipped
plt.savefig("pronlendist.eps", bbox_inches="tight", pad_inches=0)
plt.show()
